apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: card-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bank/banking-platform
    targetRevision: HEAD
    path: infrastructure/helm/charts/card-service
  destination:
    server: https://kubernetes.default.svc
    namespace: banking-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
