stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

.standard-service:
  image: maven:3.9.5-eclipse-temurin-17
  services:
    - docker:dind
  before_script:
    - export SERVICE_NAME=$(echo $CI_JOB_NAME | sed 's/-.*//')
    - cd services/$SERVICE_NAME

account-service-build:
  extends: .standard-service
  stage: build
  script:
    - mvn clean package
    - docker build -t $ECR_REPO:$CI_COMMIT_SHORT_SHA .
    - docker push $ECR_REPO:$CI_COMMIT_SHORT_SHA
  only:
    changes:
      - services/account-service/**/*
